import "modern-css-reset/dist/reset.min.css";
import { Montserrat, Roboto_Condensed, Roboto, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/controleDespesas/ui/Navbar";
import SessionProvider from "@/components/controleDespesas/providers/SessionProvider";

const montserratSemibold = Montserrat({
  weight: ["600"],
  variable: "--font-montserrat_semibold",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "600"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${montserratSemibold.variable} ${robotoCondensed.variable} ${roboto.variable} ${poppins.variable}`}>
        <SessionProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
