import "modern-css-reset/dist/reset.min.css";
import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionProvider from "@/components/providers/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
